const express =require('express')
const routes = express.Router()
const {checkUser}= require('../middlewares/jwt')
const {getregisterpage, postregisterroute, getloginpage, postlogin, getdashboard, deposit, logout, gettransferpage, posttransferpage, callback, getwithdraw, postwithdraw, webhookurl} = require('../controllers/usercontroller')
routes.get('/register', getregisterpage)
routes.post('/register', postregisterroute)
routes.get('/login', getloginpage)
routes.post('/login',postlogin)
routes.get('/dashboard',checkUser,getdashboard)
routes.post('/dashboard',checkUser, deposit)
routes.get('/logout',checkUser, logout)
routes.get('/transfer',checkUser, gettransferpage)
routes.post('/transfer',checkUser, posttransferpage)
routes.get('/callback',checkUser,callback)
routes.get('/withdraw', checkUser,getwithdraw)
routes.post('/withdraw',checkUser,postwithdraw)
routes.post('/webhookurl',webhookurl)
module.exports=routes
